import type { AuditReport } from '@/types/audit';
import { formatDate } from './utils';

/**
 * Downloads the audit report as a JSON file (reliable fallback).
 * We use JSON because jspdf can be tricky in SSR environments.
 * A JSON file is clean, structured, and universally readable.
 */
export function downloadReportJSON(report: AuditReport): void {
  const exportData = {
    reportTitle: 'AccessMind AI — Accessibility Report',
    generatedAt: new Date().toISOString(),
    website: report.url,
    scannedAt: formatDate(report.scannedAt),
    accessibilityScore: `${report.score}/100`,
    aiSummary: report.aiSummary,
    issueCounts: {
      total: report.totalIssues,
      critical: report.critical,
      serious: report.serious,
      moderate: report.moderate,
      minor: report.minor,
    },
    auditSummary: report.summary,
    issues: report.issues.map((issue) => ({
      id: issue.id,
      title: issue.title,
      impact: issue.impact,
      wcagCriteria: issue.wcagCriteria,
      affectedElement: issue.element,
      htmlSnippet: issue.html,
      plainEnglishExplanation: issue.simpleExplanation,
      suggestedFix: issue.suggestedFix,
      learnMore: issue.helpUrl,
    })),
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], {
    type: 'application/json',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `accessmind-report-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Downloads the audit report as a plain-text file */
export function downloadReportTXT(report: AuditReport): void {
  const lines: string[] = [
    '╔══════════════════════════════════════════════════════════╗',
    '║           AccessMind AI — Accessibility Report           ║',
    '╚══════════════════════════════════════════════════════════╝',
    '',
    `Website:         ${report.url}`,
    `Scanned At:      ${formatDate(report.scannedAt)}`,
    `Score:           ${report.score}/100`,
    `Total Issues:    ${report.totalIssues}`,
    '',
    '──────────────────────────────────────────────────────────',
    'ISSUE BREAKDOWN',
    '──────────────────────────────────────────────────────────',
    `  Critical:  ${report.critical}`,
    `  Serious:   ${report.serious}`,
    `  Moderate:  ${report.moderate}`,
    `  Minor:     ${report.minor}`,
    '',
    '──────────────────────────────────────────────────────────',
    'AI SUMMARY',
    '──────────────────────────────────────────────────────────',
    report.aiSummary,
    '',
    '──────────────────────────────────────────────────────────',
    'ISSUES',
    '──────────────────────────────────────────────────────────',
    '',
    ...report.issues.flatMap((issue, i) => [
      `${i + 1}. ${issue.title} [${issue.impact.toUpperCase()}]`,
      `   WCAG: ${issue.wcagCriteria}`,
      `   Element: ${issue.element}`,
      `   Explanation: ${issue.simpleExplanation}`,
      `   Fix: ${issue.suggestedFix}`,
      `   Learn more: ${issue.helpUrl}`,
      '',
    ]),
    '──────────────────────────────────────────────────────────',
    `Generated by AccessMind AI on ${new Date().toLocaleString()}`,
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `accessmind-report-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
